var bingoList = [
    {"name": "2000ルピー", "en": "2000 Rupees", "difficulty": 8.0, "types": ["Rupee", "Ridgeland"]},
    {"name": "3000ルピー", "en": "3000 Rupees", "difficulty": 10.0, "types": ["Rupee", "Ridgeland"]},
    {"name": "3射以上の弓3つ", "en": "3 Three-shot burst bow", "difficulty": 6.0, "types": ["Bow", "Hebra", "Ridgeland"]},
    {"name": "5000ルピー", "en": "5000 Rupees", "difficulty": 17.0, "types": ["Rupee", "Ridgeland"]},
    {"name": "○○柄の盾2種", "en": "2 types of Shields from Fisherman& Emblazoned & Hunter", "difficulty": 4.5, "types": ["Shield", "Faron"]},
    {"name": "○○柄の盾3種", "en": "3 types of Shields from Fisherman& Emblazoned & Hunter", "difficulty": 7.0, "types": ["Shield", "Faron"]},
    {"name": "がんばりゲージ2周", "en": "5 Stamina Vessels", "difficulty": 46.0, "types": ["Shrine"]},
    {"name": "ここ掘れワンワンの全宝箱入手(16個)", "en": "All Dog Tresures", "difficulty": 58.0, "types": ["Side Quest", "Rupee", "Hateno", "Akkala"]},
    {"name": "ほこらチャレンジ 10つ攻略", "en": "10 Shrine Quests", "difficulty": 33.0, "types": ["Shrine Quests", "Shrine", "Shrines"]},
    {"name": "ほこらチャレンジ 11つ攻略", "en": "11 Shrine Quests", "difficulty": 37.0, "types": ["Shrine Quests", "Shrine", "Shrines"]},
    {"name": "ほこらチャレンジ 12つ攻略", "en": "12 Shrine Quests", "difficulty": 40.0, "types": ["Shrine Quests", "Shrine", "Shrines"]},
    {"name": "ほこらチャレンジ 13つ攻略", "en": "Medal of Honor: Molduga", "difficulty": 46.0, "types": ["Shrine Quests", "Shrine", "Shrines"]},
    {"name": "ほこらチャレンジ 5つ攻略", "en": "5 Shrine Quests", "difficulty": 18.0, "types": ["Shrine Quests", "Shrine"]},
    {"name": "ほこらチャレンジ 8つ攻略", "en": "8 Shrine Quests", "difficulty": 28.0, "types": ["Shrine Quests", "Shrine", "Shrines"]},
    {"name": "ほこらチャレンジ 9つ攻略", "en": "9 Shrine Quests", "difficulty": 31.0, "types": ["Shrine Quests", "Shrine", "Shrines"]},
    {"name": "ほこらチャレンジ:ガーディアンを見たい！", "en": "Guardian Slideshow' Shrine Quest", "difficulty": 19.0, "types": ["Shrine Quests", "Shrine", "Camera", "Lake", "Hateno", "Dueling Peaks", ""]},
    {"name": "ほこらチャレンジ:ドクロの左目", "en": "The Skull's Eye' Shrine Quest", "difficulty": 13.0, "types": ["Shrine Quests", "Shrine", "Camera", "Akkala", "Hateno", "Dueling Peaks", ""]},
    {"name": "ほこらチャレンジ:リトの兄弟岩", "en": "Recital at Warbler's Nest' Shrine Quest", "difficulty": 27.0, "types": ["Shrine Quests", "Shrine", "Tabantha"]},
    {"name": "ほこらチャレンジ:大蛇喰らいし龍", "en": "The Serpent's Jaws' Shrine Quest", "difficulty": 12.0, "types": ["Shrine Quests", "Shrine", "Lake"]},
    {"name": "ほこらチャレンジ:巨人三兄弟の秘密", "en": "Three Giant Brothers' Shrine Quest", "difficulty": 9.0, "types": ["Shrine Quests", "Shrine", "Faron"]},
    {"name": "ほこらチャレンジ:暗闇の試練", "en": "Shrouded Shrine' Shrine Quest", "difficulty": 5.0, "types": ["Shrine Quests", "Shrine", "Woodland"]},
    {"name": "ほこらチャレンジ:盗まれた宝珠", "en": "The Stolen Heirloom' Shrine Quest", "difficulty": 28.0, "types": ["Shrine Quests", "Shrine", "Camera", "Great Fairy", "Hateno", "Dueling Peaks", ""]},
    {"name": "ほこらチャレンジ:石碑のかけら探し", "en": "Fragmented Monument' Shrine Quest", "difficulty": 14.0, "types": ["Shrine Quests", "Shrine", "Camera", "Faron", "Hateno", "Dueling Peaks", ""]},
    {"name": "ほしのかけら3個", "en": "3 Star Fragments", "difficulty": 7.0, "types": ["Star Fragments", "Central Hyrule", "Faron"]},
    {"name": "ほしのかけら4個", "en": "4 Star Fragments", "difficulty": 10.0, "types": ["Star Fragments", "Central Hyrule", "Faron"]},
    {"name": "ほしのかけら5個", "en": "5 Star Fragments", "difficulty": 13.0, "types": ["Star Fragments", "Central Hyrule"]},
    {"name": "ゆでたまご5個", "en": "5 Hard-Boiled Egg", "difficulty": 7.0, "types": ["Egg", "Hot Spring", "Cooking"]},
    {"name": "イワロック5体討伐 (どの種でも可)", "en": "Kill 5 Talus of any kind", "difficulty": 12.0, "types": ["Kill", "Boss Monster", "Talus"]},
    {"name": "イワロック、マグロック、ガチロック1体ずつ討伐", "en": "Kill Stone&Igneo&Frost Talus", "difficulty": 18.0, "types": ["Kill", "Boss Monster", "Eldin", "Hebra", "Talus"]},
    {"name": "ウルボザの怒り", "en": "Urbosa's Fury", "difficulty": 35.0, "types": ["Divine Beast", "MainQuest", "Gerudo", "Wasteland", "Champion's Abilities"]},
    {"name": "ウワサのミツバちゃん3巻読破", "en": "Read 3 Rumor Mill", "difficulty": 6.0, "types": ["Rumor Mill"]},
    {"name": "ウワサのミツバちゃん5巻読破", "en": "Read 5Rumor Mill", "difficulty": 10.0, "types": ["Rumor Mill"]},
    {"name": "ウワサのミツバちゃん7巻読破", "en": "Read 7Rumor Mill", "difficulty": 14.0, "types": ["Rumor Mill"]},
    {"name": "エノキダ結婚", "en": "Marriage", "difficulty": 47.0, "types": ["Side Quest", "Rupee", "Hateno", "Akkala"]},
    {"name": "カッシーワのチャレンジ4種", "en": "4 Kass Quests", "difficulty": 19.0, "types": ["Kass", "Shrine Quests", "Shrine", "Shrines", "Side Quest"]},
    {"name": "カッシーワのチャレンジ5種", "en": "5 Kass Quests", "difficulty": 23.0, "types": ["Kass", "Shrine Quests", "Shrine", "Shrines", "Side Quest"]},
    {"name": "カッシーワのチャレンジ6種", "en": "6 Kass Quests", "difficulty": 29.0, "types": ["Kass", "Shrine Quests", "Shrine", "Shrines", "Side Quest"]},
    {"name": "カッシーワのチャレンジ7種", "en": "7 Kass Quests", "difficulty": 37.0, "types": ["Kass", "Shrine Quests", "Shrine", "Shrines", "Side Quest"]},
    {"name": "ガノン討伐", "en": "Beat Ganon", "difficulty": 25.0, "types": ["Divine Beast", "MainQuest", "Central Hyrule"]},
    {"name": "ガーディアンを倒して力の試練の祠10基攻略", "en": "10 A Test of Strength while Killing Guardian Scout", "difficulty": 49.0, "types": ["Guardian", "Shrine", "Akkala", "Shrines"]},
    {"name": "ガーディアンを倒して力の試練の祠3基攻略", "en": "3 A Test of Strength while Killing Guardian Scout", "difficulty": 20.0, "types": ["Guardian", "Shrine", "Shrines"]},
    {"name": "ガーディアンを倒して力の試練の祠5基攻略", "en": "5 A Test of Strength while Killing Guardian Scout", "difficulty": 27.0, "types": ["Guardian", "Shrine", "Shrines"]},
    {"name": "ガーディアンを倒して力の試練の祠8基攻略", "en": "8 A Test of Strength while Killing Guardian Scout", "difficulty": 40.0, "types": ["Guardian", "Shrine", "Akkala", "Shrines"]},
    {"name": "ギャンブルで連続大当たり", "en": "Consecutive gambling jackpots", "difficulty": 9.0, "types": ["Rupee", "Minigame", "Faron"]},
    {"name": "ゴージャス馬装備一式", "en": "Full Horse's Extravagant Set", "difficulty": 9.0, "types": ["Horse Equipment", "Horse", "Minigame", "Lake"]},
    {"name": "シーカーセンサー+", "en": "Sheikah Sensor +", "difficulty": 13.0, "types": ["Camera", "Hateno", "Dueling Peaks"]},
    {"name": "シーカータワー 4基起動", "en": "Activate 4 Towers", "difficulty": 11.0, "types": ["Tower"]},
    {"name": "シーカータワー 5基起動", "en": "Activate 5 Towers", "difficulty": 13.5, "types": ["Tower"]},
    {"name": "シーカータワー 6基起動", "en": "Read 5Rumor Mill", "difficulty": 16.0, "types": ["Tower"]},
    {"name": "シーカータワー 7基起動", "en": "Activate 5 Towers", "difficulty": 19.0, "types": ["Tower"]},
    {"name": "ズーム弓2種類", "en": "2 Bows with zoom effect", "difficulty": 7.0, "types": ["Bow"]},
    {"name": "ゾーラの兜★", "en": "Zora Helm ★", "difficulty": 11.0, "types": ["Great Fairy", "Clothes", "Lanayru"]},
    {"name": "ゾーラ装備一式", "en": "Full Zora Set", "difficulty": 35.0, "types": ["Camera", "Lanayru", "Hateno", "Side Quest"]},
    {"name": "ダルケルの護り", "en": "Daruk's Protection", "difficulty": 30.0, "types": ["Divine Beast", "MainQuest", "Eldin", "Champion's Abilities"]},
    {"name": "チュチュゼリー全種", "en": "All Chuchu Jelly", "difficulty": 5.0, "types": ["Arrow", "Plateau"]},
    {"name": "ネルドラ解放", "en": "Release Naydra", "difficulty": 10.0, "types": ["Shrine Quests", "Naydra", "Hateno"]},
    {"name": "ハイラルなぞなぞしれんでビリビリマスを見せる", "en": "Show Voltfin Trout in 'Riddles of Hyrule' Side Quest", "difficulty": 13.0, "types": ["Riddles of Hyrule", "Woodland", "Side Quest"]},
    {"name": "ハイラルなぞなぞしれんでヨロイカボチャを見せる", "en": "Show Fortified Pumpkin in 'Riddles of Hyrule' Side Quest", "difficulty": 6.0, "types": ["Riddles of Hyrule", "Woodland", "Side Quest"]},
    {"name": "ハイラル図鑑 武器 20種登録（購入不可）", "en": "20 Equipment in Compendium(without purchase)", "difficulty": 18.0, "types": ["Camera", "Compendium", "Compedium-Weapon", "Weapon"]},
    {"name": "ハイラル図鑑 武器 30種登録（購入不可）", "en": "30 Equipment in Compendium(without purchase)", "difficulty": 28.0, "types": ["Camera", "Compendium", "Compedium-Weapon", "Weapon"]},
    {"name": "ハイラル図鑑 武器 40種登録（購入不可）", "en": "40 Equipment in Compendium(without purchase)", "difficulty": 38.0, "types": ["Camera", "Compendium", "Compedium-Weapon", "Weapon"]},
    {"name": "ハイラル図鑑 生き物 20種登録（購入不可）", "en": "20 Creatures in Compendium(without purchase)", "difficulty": 22.0, "types": ["Camera", "Compendium", "Compedium-Creature"]},
    {"name": "ハイラル図鑑 生き物 30種登録（購入不可）", "en": "30 Creatures in Compendium(without purchase)", "difficulty": 34.0, "types": ["Camera", "Compendium", "Compedium-Creature"]},
    {"name": "ハイラル図鑑 生き物 40種登録（購入不可）", "en": "40 Creatures in Compendium(without purchase)", "difficulty": 50.0, "types": ["Camera", "Compendium", "Compedium-Creature"]},
    {"name": "ハイラル図鑑 魔物 20種登録（購入不可）", "en": "20 Monsters in Compendium(without purchase)", "difficulty": 25.0, "types": ["Camera", "Compendium", "Compedium-Monster"]},
    {"name": "ハイラル図鑑 魔物 30種登録（購入不可）", "en": "30 Monsters in Compendium(without purchase)", "difficulty": 36.0, "types": ["Camera", "Compendium", "Compedium-Monster"]},
    {"name": "ハイラル図鑑 魔物 40種登録（購入不可）", "en": "40 Monsters in Compendium(without purchase)", "difficulty": 53.0, "types": ["Camera", "Compendium", "Compedium-Monster"]},
    {"name": "ハイリアのフード★★★★", "en": "Hylian Hood★★★★", "difficulty": 60.0, "types": ["Hateno", "Rupee", "Great Fairy", "Clothes", "Boko Parts"]},
    {"name": "ハートミルクスープ", "en": "Creamy Heart Soup", "difficulty": 8.0, "types": ["Cooking", "Hateno"]},
    {"name": "ヒノックス10体討伐 (どの種でも可)", "en": "Kill 10 Hinox of any kind", "difficulty": 28.0, "types": ["Kill", "Boss Monster", "Hinox"]},
    {"name": "ヒノックス15体討伐 (どの種でも可)", "en": "Kill 15 Hinox of any kind", "difficulty": 42.0, "types": ["Kill", "Boss Monster", "Hinox"]},
    {"name": "ヒノックス20体討伐 (どの種でも可)", "en": "Kill 20 Hinox of any kind", "difficulty": 56.0, "types": ["Kill", "Boss Monster", "Hinox"]},
    {"name": "ヒノックス5体討伐 (どの種でも可)", "en": "Kill 5 Hinox of any kind", "difficulty": 14.0, "types": ["Kill", "Boss Monster", "Hinox"]},
    {"name": "ビタロック+", "en": "Stasis +", "difficulty": 20.0, "types": ["Camera", "Hateno", "Dueling Peaks"]},
    {"name": "マモノ馬装備一式", "en": "Monster Saddle and Bridle", "difficulty": 58.0, "types": ["Horse Equipment", "Divine Beast", "MainQuest", "Champion's Abilities"]},
    {"name": "ミニゲーム10種クリア", "en": "10 Minigames", "difficulty": 65.0, "types": ["Minigame", "Lake", "Horse Equipment"]},
    {"name": "ミニゲーム11種クリア", "en": "11 Minigames", "difficulty": 77.0, "types": ["Minigame", "Lake", "Horse Equipment"]},
    {"name": "ミニゲーム3種クリア", "en": "3 Minigames", "difficulty": 13.0, "types": ["Minigame", "Lake"]},
    {"name": "ミニゲーム5種クリア", "en": "5 Minigames", "difficulty": 22.0, "types": ["Minigame", "Lake"]},
    {"name": "ミニゲーム7種クリア", "en": "7 Minigames", "difficulty": 32.0, "types": ["Minigame", "Lake", "Horse Equipment"]},
    {"name": "ミニゲーム8種クリア", "en": "8 Minigames", "difficulty": 36.0, "types": ["Minigame", "Lake", "Horse Equipment"]},
    {"name": "ミニゲーム9種クリア", "en": "9 Minigames", "difficulty": 50.0, "types": ["Minigame", "Lake", "Horse Equipment"]},
    {"name": "ミニゲーム:雪玉ボウルでストライク", "en": "Strike in bowling mini-game", "difficulty": 5.0, "types": ["Minigame", "Hebra"]},
    {"name": "ミニゲーム:飛行訓練 的を20個射抜く", "en": "20 Targets in Flight Range Minigame", "difficulty": 22.0, "types": ["Divine Beast", "Tabantha", "Hebra", "Champion's Abilities"]},
    {"name": "ミニゲーム:鳥人間チャレンジ 7000m以上滑空", "en": "7000m in the Gliding Minigame", "difficulty": 4.0, "types": ["Minigame", "Ridgeland"]},
    {"name": "ミニチャレンジ10個", "en": "10 Side Quests", "difficulty": 35.0, "types": ["Side Quest", "Dueling Peaks"]},
    {"name": "ミニチャレンジ15個", "en": "15 Side Quests", "difficulty": 56.0, "types": ["Side Quest", "Dueling Peaks"]},
    {"name": "ミニチャレンジ20個", "en": "20 Side Quests", "difficulty": 74.0, "types": ["Side Quest", "Dueling Peaks", "Camera", "Akkala"]},
    {"name": "ミニチャレンジ: ゲルドの至宝 雷鳴の兜！", "en": "The Thunder Helm' Side Quest", "difficulty": 60.0, "types": ["Side Quest", "Divine Beast", "MainQuest", "Gerudo", "Wasteland", "Champion's Abilities", ""]},
    {"name": "ミニチャレンジ:ぴかぴかのルミーしれん", "en": "Legendary Rabbit Trial' Side Quest", "difficulty": 16.0, "types": ["Camera", "Woodland", "Hateno", "Dueling Peaks", "Side Quest"]},
    {"name": "ミニチャレンジ:もう一人の研究者", "en": "Robbie's Research' Side Quest", "difficulty": 12.0, "types": ["Camera", "Akkala", "Hateno", "Dueling Peaks", "Side Quest"]},
    {"name": "ミニチャレンジ:コログしれん", "en": "Korok Trials' Side Quest", "difficulty": 21.0, "types": ["Shrine", "Minigame", "Shrine Quests", "Woodland", "Shrines", "Side Quest", ""]},
    {"name": "ミニチャレンジ:ハイラルなぞなぞしれん", "en": "Riddles of Hyrule' Side Quest", "difficulty": 28.0, "types": ["Riddles of Hyrule", "Boss Monster", "Woodland", "Side Quest"]},
    {"name": "ミニチャレンジ:ホタル ノ ヒカリ", "en": "By Firefly's Light' Side Quest", "difficulty": 20.0, "types": ["Great Fairy", "Camera", "Hateno", "Dueling Peaks", "Side Quest"]},
    {"name": "ミニチャレンジ:八人目の英雄", "en": "The Eighth Heroine' Side Quest", "difficulty": 25.0, "types": ["Camera", "Gerudo", "Hateno", "Dueling Peaks"]},
    {"name": "ミニチャレンジ:奪われた漁場", "en": "Take Back the Sea' Side Quest", "difficulty": 7.0, "types": ["Faron", "Side Quest"]},
    {"name": "ミニチャレンジ:巨大クジラの化石", "en": "Leviathan Bones' Side Quest", "difficulty": 29.0, "types": ["Camera", "Eldin", "Wasteland", "Hebra", "Hateno", "Side Quest", ""]},
    {"name": "ミニチャレンジ:幼き武器マニア", "en": "The Weapon Connoisseur' Side Quest", "difficulty": 60.0, "types": ["Hateno", "Rupee", "Weapon", "Castle", "Akkala"]},
    {"name": "ミニチャレンジ:忘れられた剣", "en": "The Forgotten Sword' Side Quest", "difficulty": 30.0, "types": ["Rupee", "Wasteland", "Gerudo", "Camera", "Side Quest"]},
    {"name": "ミニチャレンジ:消えたコッコちゃん", "en": "Flown the Coop' Side Quest", "difficulty": 9.0, "types": ["Dueling Peaks", "Side Quest"]},
    {"name": "ミニチャレンジ:解放 さらなる力", "en": "Slated for Upgrades' Side Quest", "difficulty": 28.0, "types": ["Camera", "Hateno", "Dueling Peaks", "Side Quest"]},
    {"name": "ミファーの祈り", "en": "Mipha's Grace", "difficulty": 27.0, "types": ["Divine Beast", "MainQuest", "Lanayru", "Champion's Abilities"]},
    {"name": "メインチャレンジ4個達成", "en": "4 MainQuests", "difficulty": 14.0, "types": ["MainQuest", "Camera", "Hateno", "Dueling Peaks"]},
    {"name": "メインチャレンジ5個達成", "en": "5 MainQuests", "difficulty": 18.0, "types": ["MainQuest", "Camera", "Hateno", "Dueling Peaks"]},
    {"name": "メインチャレンジ6個達成", "en": "6 MainQuests", "difficulty": 24.5, "types": ["MainQuest", "Camera", "Hateno", "Dueling Peaks"]},
    {"name": "メインチャレンジ7個達成", "en": "7 MainQuests", "difficulty": 30.0, "types": ["MainQuest", "Divine Beast", "Camera", "Hateno", "Dueling Peaks", "Champion's Abilities", ""]},
    {"name": "メインチャレンジ8個達成", "en": "8 MainQuests", "difficulty": 46.0, "types": ["MainQuest", "Divine Beast", "Camera", "Hateno", "Champion's Abilities"]},
    {"name": "メインチャレンジ9個達成", "en": "9 MainQuests", "difficulty": 60.0, "types": ["MainQuest", "Divine Beast", "Camera", "Hateno", "Champion's Abilities"]},
    {"name": "メインチャレンジ：ウツシエの記憶", "en": "Captured Memories' Main Quest", "difficulty": 60.0, "types": ["Camera", "Hateno", "Dueling Peaks"]},
    {"name": "メインチャレンジ：勇者の剣", "en": "The Hero's Sword' Main Quest", "difficulty": 80.0, "types": ["Shrine", "MainQuest", "Woodland", "Shrines", "Spirit Orb"]},
    {"name": "ライネル、ヒノックス、モルドラの素材計5種", "en": "5 Different Monster Parts From Lynel&Hinox&Molduga", "difficulty": 9.0, "types": ["Boss Monster", "Castle", "Hinox", "Molduga", "Lynel"]},
    {"name": "ライネル、ヒノックス、モルドラの素材計6種", "en": "6 Different Monster Parts From Lynel&Hinox&Molduga", "difficulty": 13.0, "types": ["Boss Monster", "Castle", "Hinox", "Molduga", "Lynel"]},
    {"name": "ライネル、ヒノックス、モルドラの素材計7種", "en": "7 Different Monster Parts From Lynel&Hinox&Molduga", "difficulty": 16.0, "types": ["Boss Monster", "Castle", "Hinox", "Molduga", "Lynel"]},
    {"name": "ライネル全討伐(23匹)", "en": "Kill All Lynels", "difficulty": 40.0, "types": ["Castle", "Kill", "Boss Monster", "Lynel"]},
    {"name": "ラジークキラーの証", "en": "Medal of Honor: Molduga", "difficulty": 43.0, "types": ["Kill", "Boss Monster", "Wasteland", "Akkala", "Molduga"]},
    {"name": "リザルフォスの素材5種", "en": "5 Different Lizalfos Parts", "difficulty": 8.0, "types": ["Lizalfos Parts", "Wasteland", "Castle"]},
    {"name": "リザルフォスの素材6種", "en": "6 Different Lizalfos Parts", "difficulty": 11.0, "types": ["Lizalfos Parts", "Wasteland", "Castle"]},
    {"name": "リモコンバクダン+", "en": "Remote Bomb +", "difficulty": 18.0, "types": ["Camera", "Hateno", "Dueling Peaks"]},
    {"name": "リーバルの猛り", "en": "Revali's Gale", "difficulty": 18.0, "types": ["Divine Beast", "MainQuest", "Tabantha", "Hebra", "Champion's Abilities"]},
    {"name": "全ての塔を起動", "en": "Activate All Towers", "difficulty": 40.0, "types": ["Tower"]},
    {"name": "凍結無効", "en": "Unfreezable (without potion)", "difficulty": 35.0, "types": ["Hebra", "Tabantha", "Rupee", "Great Fairy", "Clothes"]},
    {"name": "加速泳ぎがんばり長持ち", "en": "Swim Dash Stamina Up", "difficulty": 51.0, "types": ["Camera", "Lanayru", "Rupee", "Great Fairy", "Clothes"]},
    {"name": "古代の巨大なコア3個", "en": "3 Giant Ancient Core", "difficulty": 9.5, "types": ["Giant Ancient Core", "Shrine", "Akkala"]},
    {"name": "古代の巨大なコア4個", "en": "4 Giant Ancient Core", "difficulty": 13.5, "types": ["Giant Ancient Core", "Shrine", "Akkala"]},
    {"name": "古代の巨大なコア5個", "en": "5 Giant Ancient Core", "difficulty": 17.0, "types": ["Giant Ancient Core", "Shrine", "Akkala"]},
    {"name": "古代の巨大なコア6個", "en": "6 Giant Ancient Core", "difficulty": 22.0, "types": ["Giant Ancient Core", "Shrine", "Akkala"]},
    {"name": "古代兵装弓", "en": "Ancient Bow", "difficulty": 27.0, "types": ["Rupee", "Bow", "Castle", "Akkala"]},
    {"name": "古代兵装武器", "en": "Ancient Weapon", "difficulty": 25.0, "types": ["Rupee", "Weapon", "Castle", "Akkala"]},
    {"name": "古代兵装盾", "en": "Ancient Shield", "difficulty": 28.0, "types": ["Rupee", "Shield", "Castle", "Akkala"]},
    {"name": "古代兵装矢10本", "en": "10 Ancient Arrows", "difficulty": 5.0, "types": ["Arrow", "Castle"]},
    {"name": "古代兵装矢15本", "en": "15 Ancient Arrows", "difficulty": 7.0, "types": ["Arrow", "Castle"]},
    {"name": "古代兵装矢20本", "en": "20 Ancient Arrows", "difficulty": 11.0, "types": ["Arrow", "Castle"]},
    {"name": "古代兵装矢25本", "en": "25 Ancient Arrows", "difficulty": 24.0, "types": ["Arrow", "Camera", "Castle", "Akkala", "Hateno", "Dueling Peaks", ""]},
    {"name": "古代兵装防具", "en": "Ancient Armor", "difficulty": 32.0, "types": ["Rupee", "Clothes", "Castle", "Akkala"]},
    {"name": "夜光シリーズ一式を着て自撮り", "en": "Selfie wearing a set of Radiant series", "difficulty": 25.0, "types": ["Rupee", "Camera", "Wasteland"]},
    {"name": "夜光防具一式", "en": "Full Radiant Set", "difficulty": 17.0, "types": ["Clothes", "Rupee", "Wasteland"]},
    {"name": "大事なもの11枠", "en": "11 Different Key Items", "difficulty": 22.0, "types": ["Minigame", "Key Items", "Horse Equipment"]},
    {"name": "大事なもの12枠", "en": "12 Different Key Items", "difficulty": 35.0, "types": ["Minigame", "Key Items", "Horse Equipment"]},
    {"name": "大事なもの13枠", "en": "13 Different Key Items", "difficulty": 55.0, "types": ["Minigame", "Key Items", "MainQuest", "Horse Equipment"]},
    {"name": "大事なもの7枠", "en": "7 Different Key Items", "difficulty": 16.0, "types": ["Minigame", "Key Items", "Horse Equipment"]},
    {"name": "大妖精 2人解放", "en": "Pay 2 Great Fairies", "difficulty": 9.0, "types": ["Great Fairy", "Rupee", "Dueling Peaks"]},
    {"name": "大妖精 3人解放", "en": "Pay 3 Great Fairies", "difficulty": 15.0, "types": ["Great Fairy", "Rupee", "Dueling Peaks"]},
    {"name": "家を買う", "en": "Buy a House", "difficulty": 16.0, "types": ["Rupee", "Hateno"]},
    {"name": "小型ガーディアン（中位）2体討伐", "en": "Kill 2 Guardian Scout III", "difficulty": 11.0, "types": ["Guardian", "Kill"]},
    {"name": "小型ガーディアン（中位）3体討伐", "en": "Kill 3 Guardian Scout III", "difficulty": 14.0, "types": ["Guardian", "Kill"]},
    {"name": "小型ガーディアン（極位）1体討伐", "en": "Kill Guardian Scout IV", "difficulty": 8.0, "types": ["Guardian", "Kill", "Central Hyrule"]},
    {"name": "小型ガーディアン（極位）2体討伐", "en": "Kill 2 Guardian Scout IV", "difficulty": 13.0, "types": ["Guardian", "Kill", "Hebra"]},
    {"name": "小型ガーディアン（極位）3体討伐", "en": "Kill 3 Guardian Scout IV", "difficulty": 16.0, "types": ["Guardian", "Kill", "Hebra"]},
    {"name": "木の枝6本", "en": "6 Tree Branches", "difficulty": 2.0, "types": ["Weapon", "Plateau"]},
    {"name": "森人武器盾弓", "en": "Forest Dweller’s Weapon&Shield&Bow", "difficulty": 3.0, "types": ["Weapon", "Woodland"]},
    {"name": "武器10種", "en": "10 Different Weapon", "difficulty": 12.0, "types": ["Weapon", "Koroks", "Castle", "Dueling Peaks"]},
    {"name": "武器11種", "en": "11 Different Weapon", "difficulty": 14.0, "types": ["Weapon", "Koroks", "Castle", "Central Hyrule", "Dueling Peaks"]},
    {"name": "武器12種", "en": "12 Different Weapon", "difficulty": 18.5, "types": ["Weapon", "Koroks", "Castle", "Central Hyrule", "Dueling Peaks"]},
    {"name": "武器13種", "en": "13 Different Weapon", "difficulty": 26.0, "types": ["Weapon", "Koroks", "Castle", "Central Hyrule", "Dueling Peaks"]},
    {"name": "武器14種", "en": "14 Different Weapon", "difficulty": 37.0, "types": ["Weapon", "Koroks", "Castle", "Central Hyrule", "Dueling Peaks"]},
    {"name": "武器15種", "en": "15 Different Weapon", "difficulty": 54.5, "types": ["Weapon", "Koroks", "Castle", "Central Hyrule", "Dueling Peaks", "Woodland", ""]},
    {"name": "武器16種", "en": "16 Different Weapon", "difficulty": 76.0, "types": ["Weapon", "Koroks", "Castle", "Central Hyrule", "Dueling Peaks", "Woodland", ""]},
    {"name": "武器8種", "en": "8 Different Weapon", "difficulty": 3.0, "types": ["Weapon", "Castle"]},
    {"name": "武器9種", "en": "9 Different Weapon", "difficulty": 9.5, "types": ["Weapon", "Koroks", "Castle", "Dueling Peaks"]},
    {"name": "炎無効", "en": "Fireproof (without potion)", "difficulty": 39.0, "types": ["Eldin", "Rupee", "Great Fairy", "Clothes"]},
    {"name": "熱砂の鉢がね★", "en": "Desert Voe Headband ★", "difficulty": 15.0, "types": ["Great Fairy", "Clothes", "Rupee", "Wasteland"]},
    {"name": "盾サーフィンミニゲームで風凪の盾", "en": "Get Kite Shield in the Shield Surf Minigame", "difficulty": 16.0, "types": ["Shield", "Minigame", "Hebra"]},
    {"name": "祠 10基攻略", "en": "10 Shrines", "difficulty": 16.0, "types": ["Shrine", "Central Hyrule", "Shrines", "Spirit Orb"]},
    {"name": "祠 15基攻略", "en": "15 Shrines", "difficulty": 29.0, "types": ["Shrine", "Central Hyrule", "Shrines", "Spirit Orb"]},
    {"name": "祠 20基攻略", "en": "20 Shrines", "difficulty": 41.0, "types": ["Shrine", "Central Hyrule", "Shrines", "Spirit Orb"]},
    {"name": "祠 25基攻略", "en": "25 Shrines", "difficulty": 52.0, "types": ["Shrine", "Central Hyrule", "Shrines", "Spirit Orb"]},
    {"name": "祠 28基攻略", "en": "28 Shrines", "difficulty": 60.0, "types": ["Shrine", "Central Hyrule", "Shrines", "Spirit Orb"]},
    {"name": "祠 30基攻略", "en": "30 Shrines", "difficulty": 65.0, "types": ["Shrine", "Central Hyrule", "Shrines", "Spirit Orb"]},
    {"name": "秘湯でゆでたまごを作る", "en": "Boiled eggs in a secret hot spring", "difficulty": 4.0, "types": ["Egg", "Secret Hot Spring", "Hot Spring"]},
    {"name": "秘湯３カ所に浸かる", "en": "Soak in 3 secret hot springs", "difficulty": 13.0, "types": ["Secret Hot Spring", "Hot Spring", "Hebra"]},
    {"name": "竜の素材5種", "en": "5 Different Dragon's Parts", "difficulty": 10.0, "types": ["Dragon's Parts", "Naydra", "Farosh", "Dinraal", "Castle"]},
    {"name": "竜の素材6種", "en": "6 Different Dragon's Parts", "difficulty": 18.0, "types": ["Dragon's Parts", "Naydra", "Farosh", "Dinraal", "Castle", "Faron", ""]},
    {"name": "耐火の石兜★", "en": "Flamebreaker Helm ★", "difficulty": 20.0, "types": ["Great Fairy", "Clothes", "Rupee", "Eldin", "Ridgeland"]},
    {"name": "英傑能力2つ", "en": "2 Champion's Abilities", "difficulty": 50.0, "types": ["Divine Beast", "MainQuest", "Champion's Abilities"]},
    {"name": "英傑能力3つ", "en": "3 Champion's Abilities", "difficulty": 75.0, "types": ["Divine Beast", "MainQuest", "Champion's Abilities"]},
    {"name": "薬8種", "en": "8 types of potion", "difficulty": 12.0, "types": ["Cooking"]},
    {"name": "蛮族装備一式", "en": "Full Barbarian Set", "difficulty": 10.0, "types": ["Clothes", "Shrine", "Akkala", "Hebra"]},
    {"name": "記憶ムービー3個", "en": "Collect 3 Memories", "difficulty": 8.0, "types": ["Memories", "Camera", "Central Hyrule", "Hateno", "Dueling Peaks"]},
    {"name": "記憶ムービー5個", "en": "Collect 5 Memories", "difficulty": 12.0, "types": ["Memories", "Camera", "Hateno", "Dueling Peaks"]},
    {"name": "記憶ムービー7個", "en": "Collect 7 Memories", "difficulty": 19.0, "types": ["Memories", "Camera", "Hateno", "Dueling Peaks"]},
    {"name": "速度5の馬を登録する", "en": "Register a Horse with 5 Speed", "difficulty": 9.0, "types": ["Horse", "Lake"]},
    {"name": "防具11種", "en": "11 Armors", "difficulty": 18.0, "types": ["Clothes", "Rupee"]},
    {"name": "防具14種", "en": "14 Armors", "difficulty": 29.0, "types": ["Clothes", "Rupee"]},
    {"name": "防具5種", "en": "5 Armors", "difficulty": 5.5, "types": ["Clothes", "Rupee"]},
    {"name": "防具7種", "en": "7 Armors", "difficulty": 8.0, "types": ["Clothes", "Rupee"]},
    {"name": "雪よけの羽飾り★", "en": "Snowquill Headdress ★", "difficulty": 14.0, "types": ["Great Fairy", "Clothes", "Rupee", "Tabantha", "Hebra", "Ridgeland", ""]},
    {"name": "雷無効", "en": "Unshockable (without potion)", "difficulty": 38.0, "types": ["Rupee", "Great Fairy", "Clothes", "Ridgeland", "Faron"]},
    {"name": "電気の矢50本", "en": "50 Shock Arrows", "difficulty": 12.0, "types": ["Arrow", "Rupee"]},
    {"name": "馬を蘇生する", "en": "Revive a horse", "difficulty": 9.5, "types": ["Rupee", "Horse", "Lake"]},
    {"name": "騎士のくら", "en": "Knight's Saddle", "difficulty": 9.0, "types": ["Horse Equipment", "Minigame", "Lake"]}
];
