var bingoList = [
    [
        { "name": "木の枝6本", "en": "6 Tree Branches", "types": ["Weapon", "Plateau"] },
        { "name": "ミニゲーム:雪玉ボウルでストライク", "en": "Strike in bowling mini-game", "types": ["Minigame", "Hebra"] },
        { "name": "ミニゲーム:鳥人間チャレンジ 7000m以上滑空", "en": "7000m in the Gliding Minigame", "types": ["Minigame", "Ridgeland"] },
        { "name": "森人武器盾弓", "en": "Forest Dweller’s Weapon&Shield&Bow", "types": ["Weapon", "Woodland"] },
        { "name": "武器8種", "en": "8 Different Weapon", "types": ["Weapon", "Castle"] },
    ], [
        { "name": "ほこらチャレンジ:暗闇の試練", "en": "Shrouded Shrine' Shrine Quest", "types": ["Shrine Quests", "Shrine", "Woodland"] },
        { "name": "秘湯でゆでたまごを作る", "en": "Boiled eggs in a secret hot spring", "types": ["Egg", "Secret Hot Spring", "Hot Spring"] },
        { "name": "○○柄の盾2種", "en": "2 types of Shields from Fisherman& Emblazoned & Hunter", "types": ["Shield", "Faron"] },
        { "name": "チュチュゼリー全種", "en": "All Chuchu Jelly", "types": ["Arrow", "Plateau"] },
        { "name": "古代兵装矢10本", "en": "10 Ancient Arrows", "types": ["Arrow", "Castle"] },
        { "name": "防具5種", "en": "5 Armors", "types": ["Clothes", "Rupee"] },
    ], [
        { "name": "3射以上の弓3つ", "en": "3 Three-shot burst bow", "types": ["Bow", "Hebra", "Ridgeland"] },
        { "name": "ウワサのミツバちゃん3巻読破", "en": "Read 3 Rumor Mill", "types": ["Rumor Mill"] },
        { "name": "ハイラルなぞなぞしれんでヨロイカボチャを見せる", "en": "Show Fortified Pumpkin in 'Riddles of Hyrule' Side Quest", "types": ["Riddles of Hyrule", "Woodland", "Side Quest"] },
        { "name": "ミニチャレンジ:奪われた漁場", "en": "Take Back the Sea' Side Quest", "types": ["Faron", "Side Quest"] },
        { "name": "記憶ムービー3個", "en": "Collect 3 Memories", "types": ["Memories", "Camera", "Central Hyrule", "Hateno", "Dueling Peaks"] },
        { "name": "○○柄の盾3種", "en": "3 types of Shields from Fisherman& Emblazoned & Hunter", "types": ["Shield", "Faron"] },
        { "name": "シーカータワー 4基起動", "en": "Activate 4 Towers", "types": ["Tower"] },
        { "name": "ズーム弓2種類", "en": "2 Bows with zoom effect", "types": ["Bow"] },
        { "name": "ほしのかけら3個", "en": "3 Star Fragments", "types": ["Star Fragments", "Central Hyrule", "Faron"] },
        { "name": "ゆでたまご5個", "en": "5 Hard-Boiled Egg", "types": ["Egg", "Hot Spring", "Cooking"] },
        { "name": "古代兵装矢15本", "en": "15 Ancient Arrows", "types": ["Arrow", "Castle"] },
        { "name": "大妖精 2人解放", "en": "Pay 2 Great Fairies", "types": ["Great Fairy", "Rupee", "Dueling Peaks"] },
        { "name": "2000ルピー", "en": "2000 Rupees", "types": ["Rupee", "Ridgeland"] },
        { "name": "ハートミルクスープ", "en": "Creamy Heart Soup", "types": ["Cooking", "Hateno"] },
        { "name": "ほこらチャレンジ:巨人三兄弟の秘密", "en": "Three Giant Brothers' Shrine Quest", "types": ["Shrine Quests", "Shrine", "Faron"] },
        { "name": "ミニゲーム3種クリア", "en": "3 Minigames", "types": ["Minigame", "Lake"] },
        { "name": "ミニチャレンジ:消えたコッコちゃん", "en": "Flown the Coop' Side Quest", "types": ["Dueling Peaks", "Side Quest"] },
        { "name": "リザルフォスの素材5種", "en": "5 Different Lizalfos Parts", "types": ["Lizalfos Parts", "Wasteland", "Castle"] },
        { "name": "騎士のくら", "en": "Knight's Saddle", "types": ["Horse Equipment", "Minigame", "Lake"] },
        { "name": "小型ガーディアン（極位）1体討伐", "en": "Kill Guardian Scout IV", "types": ["Guardian", "Kill", "Central Hyrule"] },
        { "name": "防具7種", "en": "7 Armors", "types": ["Clothes", "Rupee"] },
    ], [
        { "name": "シーカータワー 5基起動", "en": "Activate 5 Towers", "types": ["Tower"] },
        { "name": "ギャンブルで連続大当たり", "en": "Consecutive gambling jackpots", "types": ["Rupee", "Minigame", "Faron"] },
        { "name": "ゴージャス馬装備一式", "en": "Full Horse's Extravagant Set", "types": ["Horse Equipment", "Horse", "Minigame", "Lake"] },
        { "name": "ライネル、ヒノックス、モルドラの素材計5種", "en": "5 Different Monster Parts From Lynel&Hinox&Molduga", "types": ["Boss Monster", "Castle", "Hinox", "Molduga", "Lynel"] },
        { "name": "速度5の馬を登録する", "en": "Register a Horse with 5 Speed", "types": ["Horse", "Lake"] },
        { "name": "武器9種", "en": "9 Different Weapon", "types": ["Weapon", "Koroks", "Castle", "Dueling Peaks"] },
        { "name": "記憶ムービー5個", "en": "Collect 5 Memories", "types": ["Memories", "Camera", "Hateno", "Dueling Peaks"] },
        { "name": "古代の巨大なコア3個", "en": "3 Giant Ancient Core", "types": ["Giant Ancient Core", "Shrine", "Akkala"] },
        { "name": "馬を蘇生する", "en": "Revive a horse", "types": ["Rupee", "Horse", "Lake"] },
        { "name": "3000ルピー", "en": "3000 Rupees", "types": ["Rupee", "Ridgeland"] },
        { "name": "ウワサのミツバちゃん5巻読破", "en": "Read 5Rumor Mill", "types": ["Rumor Mill"] },
        { "name": "シーカータワー 6基起動", "en": "Read 5Rumor Mill", "types": ["Tower"] },
        { "name": "ネルドラ解放", "en": "Release Naydra", "types": ["Shrine Quests", "Naydra", "Hateno"] },
        { "name": "ほしのかけら4個", "en": "4 Star Fragments", "types": ["Star Fragments", "Central Hyrule", "Faron"] },
        { "name": "ミニチャレンジ:もう一人の研究者", "en": "Robbie's Research' Side Quest", "types": ["Camera", "Akkala", "Hateno", "Dueling Peaks", "Side Quest"] },
        { "name": "メインチャレンジ4個達成", "en": "4 MainQuests", "types": ["MainQuest", "Camera", "Hateno", "Dueling Peaks"] },
        { "name": "雪よけの羽飾り★", "en": "Snowquill Headdress ★", "types": ["Great Fairy", "Clothes", "Rupee", "Tabantha", "Hebra", "Ridgeland", ""] },
        { "name": "蛮族装備一式", "en": "Full Barbarian Set", "types": ["Clothes", "Shrine", "Akkala", "Hebra"] },
        { "name": "竜の素材5種", "en": "5 Different Dragon's Parts", "types": ["Dragon's Parts", "Naydra", "Farosh", "Dinraal", "Castle"] },
    ], [
        { "name": "ゾーラの兜★", "en": "Zora Helm ★", "types": ["Great Fairy", "Clothes", "Lanayru"] },
        { "name": "ほこらチャレンジ:ドクロの左目", "en": "The Skull's Eye' Shrine Quest", "types": ["Shrine Quests", "Shrine", "Camera", "Akkala", "Hateno", "Dueling Peaks", ""] },
        { "name": "ほこらチャレンジ:石碑のかけら探し", "en": "Fragmented Monument' Shrine Quest", "types": ["Shrine Quests", "Shrine", "Camera", "Faron", "Hateno", "Dueling Peaks", ""] },
        { "name": "ほこらチャレンジ:大蛇喰らいし龍", "en": "The Serpent's Jaws' Shrine Quest", "types": ["Shrine Quests", "Shrine", "Lake"] },
        { "name": "リザルフォスの素材6種", "en": "6 Different Lizalfos Parts", "types": ["Lizalfos Parts", "Wasteland", "Castle"] },
        { "name": "古代兵装矢20本", "en": "20 Ancient Arrows", "types": ["Arrow", "Castle"] },
        { "name": "小型ガーディアン（中位）2体討伐", "en": "Kill 2 Guardian Scout III", "types": ["Guardian", "Kill"] },
        { "name": "武器10種", "en": "10 Different Weapon", "types": ["Weapon", "Koroks", "Castle", "Dueling Peaks"] },
        { "name": "イワロック5体討伐 (どの種でも可)", "en": "Kill 5 Talus of any kind", "types": ["Kill", "Boss Monster", "Talus"] },
        { "name": "シーカータワー 7基起動", "en": "Activate 5 Towers", "types": ["Tower"] },
        { "name": "大妖精 3人解放", "en": "Pay 3 Great Fairies", "types": ["Great Fairy", "Rupee", "Dueling Peaks"] },
        { "name": "電気の矢50本", "en": "50 Shock Arrows", "types": ["Arrow", "Rupee"] },
        { "name": "熱砂の鉢がね★", "en": "Desert Voe Headband ★", "types": ["Great Fairy", "Clothes", "Rupee", "Wasteland"] },
        { "name": "武器11種", "en": "11 Different Weapon", "types": ["Weapon", "Koroks", "Castle", "Central Hyrule", "Dueling Peaks"] },
        { "name": "薬8種", "en": "8 types of potion", "types": ["Cooking"] },
        { "name": "シーカーセンサー+", "en": "Sheikah Sensor +", "types": ["Camera", "Hateno", "Dueling Peaks"] },
        { "name": "ハイラルなぞなぞしれんでビリビリマスを見せる", "en": "Show Voltfin Trout in 'Riddles of Hyrule' Side Quest", "types": ["Riddles of Hyrule", "Woodland", "Side Quest"] },
        { "name": "ほしのかけら5個", "en": "5 Star Fragments", "types": ["Star Fragments", "Central Hyrule"] },
        { "name": "ミニチャレンジ:ぴかぴかのルミーしれん", "en": "Legendary Rabbit Trial' Side Quest", "types": ["Camera", "Woodland", "Hateno", "Dueling Peaks", "Side Quest"] },
        { "name": "メインチャレンジ5個達成", "en": "5 MainQuests", "types": ["MainQuest", "Camera", "Hateno", "Dueling Peaks"] },
        { "name": "ライネル、ヒノックス、モルドラの素材計6種", "en": "6 Different Monster Parts From Lynel&Hinox&Molduga", "types": ["Boss Monster", "Castle", "Hinox", "Molduga", "Lynel"] },
        { "name": "リモコンバクダン+", "en": "Remote Bomb +", "types": ["Camera", "Hateno", "Dueling Peaks"] },
        { "name": "家を買う", "en": "Buy a House", "types": ["Rupee", "Hateno"] },
        { "name": "小型ガーディアン（極位）2体討伐", "en": "Kill 2 Guardian Scout IV", "types": ["Guardian", "Kill", "Hebra"] },
        { "name": "秘湯３カ所に浸かる", "en": "Soak in 3 secret hot springs", "types": ["Secret Hot Spring", "Hot Spring", "Hebra"] },
        { "name": "祠 10基攻略", "en": "10 Shrines", "types": ["Shrine", "Central Hyrule", "Shrines", "Spirit Orb"] },
    ], [
        { "name": "古代の巨大なコア4個", "en": "4 Giant Ancient Core", "types": ["Giant Ancient Core", "Shrine", "Akkala"] },
        { "name": "ウワサのミツバちゃん7巻読破", "en": "Read 7Rumor Mill", "types": ["Rumor Mill"] },
        { "name": "ヒノックス5体討伐 (どの種でも可)", "en": "Kill 5 Hinox of any kind", "types": ["Kill", "Boss Monster", "Hinox"] },
        { "name": "ミニゲーム5種クリア", "en": "5 Minigames", "types": ["Minigame", "Lake"] },
        { "name": "盾サーフィンミニゲームで風凪の盾", "en": "Get Kite Shield in the Shield Surf Minigame", "types": ["Shield", "Minigame", "Hebra"] },
        { "name": "小型ガーディアン（中位）3体討伐", "en": "Kill 3 Guardian Scout III", "types": ["Guardian", "Kill"] },
        { "name": "大事なもの7枠", "en": "7 Different Key Items", "types": ["Minigame", "Key Items", "Horse Equipment"] },
        { "name": "カッシーワのチャレンジ4種", "en": "4 Kass Quests", "types": ["Kass", "Shrine Quests", "Shrine", "Shrines", "Side Quest"] },
        { "name": "ビタロック+", "en": "Stasis +", "types": ["Camera", "Hateno", "Dueling Peaks"] },
        { "name": "ほこらチャレンジ 5つ攻略", "en": "5 Shrine Quests", "types": ["Shrine Quests", "Shrine"] },
        { "name": "リーバルの猛り", "en": "Revali's Gale", "types": ["Divine Beast", "MainQuest", "Tabantha", "Hebra", "Champion's Abilities"] },
        { "name": "記憶ムービー7個", "en": "Collect 7 Memories", "types": ["Memories", "Camera", "Hateno", "Dueling Peaks"] },
        { "name": "武器12種", "en": "12 Different Weapon", "types": ["Weapon", "Koroks", "Castle", "Central Hyrule", "Dueling Peaks"] },
    ], [
        { "name": "ほこらチャレンジ:ガーディアンを見たい！", "en": "Guardian Slideshow' Shrine Quest", "types": ["Shrine Quests", "Shrine", "Camera", "Lake", "Hateno", "Dueling Peaks", ""] },
        { "name": "ライネル、ヒノックス、モルドラの素材計7種", "en": "7 Different Monster Parts From Lynel&Hinox&Molduga", "types": ["Boss Monster", "Castle", "Hinox", "Molduga", "Lynel"] },
        { "name": "小型ガーディアン（極位）3体討伐", "en": "Kill 3 Guardian Scout IV", "types": ["Guardian", "Kill", "Hebra"] },
        { "name": "5000ルピー", "en": "5000 Rupees", "types": ["Rupee", "Ridgeland"] },
        { "name": "ミニチャレンジ:コログしれん", "en": "Korok Trials' Side Quest", "types": ["Shrine", "Minigame", "Shrine Quests", "Woodland", "Shrines", "Side Quest", ""] },
        { "name": "古代の巨大なコア5個", "en": "5 Giant Ancient Core", "types": ["Giant Ancient Core", "Shrine", "Akkala"] },
        { "name": "耐火の石兜★", "en": "Flamebreaker Helm ★", "types": ["Great Fairy", "Clothes", "Rupee", "Eldin", "Ridgeland"] },
        { "name": "夜光防具一式", "en": "Full Radiant Set", "types": ["Clothes", "Rupee", "Wasteland"] },
        { "name": "ミニチャレンジ:ホタル ノ ヒカリ", "en": "By Firefly's Light' Side Quest", "types": ["Great Fairy", "Camera", "Hateno", "Dueling Peaks", "Side Quest"] },
    ], [
        { "name": "イワロック、マグロック、ガチロック1体ずつ討伐", "en": "Kill Stone&Igneo&Frost Talus", "types": ["Kill", "Boss Monster", "Eldin", "Hebra", "Talus"] },
        { "name": "ガーディアンを倒して力���試練の祠3基攻略", "en": "3 A Test of Strength while Killing Guardian Scout", "types": ["Guardian", "Shrine", "Shrines"] },
        { "name": "カッシーワのチャレンジ5種", "en": "5 Kass Quests", "types": ["Kass", "Shrine Quests", "Shrine", "Shrines", "Side Quest"] },
        { "name": "ハイラル図鑑 武器 20種登録（購入不可）", "en": "20 Equipment in Compendium(without purchase)", "types": ["Camera", "Compendium", "Compedium-Weapon", "Weapon"] },
        { "name": "ミニゲーム:飛行訓練 的を20個射抜く", "en": "20 Targets in Flight Range Minigame", "types": ["Divine Beast", "Tabantha", "Hebra", "Champion's Abilities"] },
        { "name": "防具11種", "en": "11 Armors", "types": ["Clothes", "Rupee"] },
        { "name": "竜の素材6種", "en": "6 Different Dragon's Parts", "types": ["Dragon's Parts", "Naydra", "Farosh", "Dinraal", "Castle", "Faron", ""] },
        { "name": "メインチャレンジ6個達成", "en": "6 MainQuests", "types": ["MainQuest", "Camera", "Hateno", "Dueling Peaks"] },
        { "name": "大事なもの11枠", "en": "11 Different Key Items", "types": ["Minigame", "Key Items", "Horse Equipment"] },
        { "name": "ガノン討伐", "en": "Beat Ganon", "types": ["Divine Beast", "MainQuest", "Central Hyrule"] },
        { "name": "ゾーラ装備一式", "en": "Full Zora Set", "types": ["Camera", "Lanayru", "Hateno", "Side Quest"] },
        { "name": "武器13種", "en": "13 Different Weapon", "types": ["Weapon", "Koroks", "Castle", "Central Hyrule", "Dueling Peaks"] },
    ], [
        { "name": "ほこらチャレンジ:盗まれた宝珠", "en": "The Stolen Heirloom' Shrine Quest", "types": ["Shrine Quests", "Shrine", "Camera", "Great Fairy", "Hateno", "Dueling Peaks", ""] },
        { "name": "ミニゲーム7種クリア", "en": "7 Minigames", "types": ["Minigame", "Lake", "Horse Equipment"] },
        { "name": "ミニチャレンジ:八人目の英雄", "en": "The Eighth Heroine' Side Quest", "types": ["Camera", "Gerudo", "Hateno", "Dueling Peaks"] },
        { "name": "ハイラル図鑑 生き物 20種登録（購入不可）", "en": "20 Creatures in Compendium(without purchase)", "types": ["Camera", "Compendium", "Compedium-Creature"] },
        { "name": "ミファーの祈り", "en": "Mipha's Grace", "types": ["Divine Beast", "MainQuest", "Lanayru", "Champion's Abilities"] },
        { "name": "古代の巨大なコア6個", "en": "6 Giant Ancient Core", "types": ["Giant Ancient Core", "Shrine", "Akkala"] },
    ], [
        { "name": "カッシーワのチャレンジ6種", "en": "6 Kass Quests", "types": ["Kass", "Shrine Quests", "Shrine", "Shrines", "Side Quest"] },
        { "name": "ほこらチャレンジ:リトの兄弟岩", "en": "Recital at Warbler's Nest' Shrine Quest", "types": ["Shrine Quests", "Shrine", "Tabantha"] },
        { "name": "メインチャレンジ7個達成", "en": "7 MainQuests", "types": ["MainQuest", "Divine Beast", "Camera", "Hateno", "Dueling Peaks", "Champion's Abilities", ""] },
        { "name": "祠 15基攻略", "en": "15 Shrines", "types": ["Shrine", "Central Hyrule", "Shrines", "Spirit Orb"] },
        { "name": "ガーディアンを倒して力の試練の祠5基攻略", "en": "5 A Test of Strength while Killing Guardian Scout", "types": ["Guardian", "Shrine", "Shrines"] },
        { "name": "ほこらチャレンジ 8つ攻略", "en": "8 Shrine Quests", "types": ["Shrine Quests", "Shrine", "Shrines"] },
        { "name": "ミニゲーム8種クリア", "en": "8 Minigames", "types": ["Minigame", "Lake", "Horse Equipment"] },
        { "name": "ミニチャレンジ:忘れられた剣", "en": "The Forgotten Sword' Side Quest", "types": ["Rupee", "Wasteland", "Gerudo", "Camera", "Side Quest"] },
        { "name": "古代兵装矢25本", "en": "25 Ancient Arrows", "types": ["Arrow", "Camera", "Castle", "Akkala", "Hateno", "Dueling Peaks", ""] },
        { "name": "ダルケルの護り", "en": "Daruk's Protection", "types": ["Divine Beast", "MainQuest", "Eldin", "Champion's Abilities"] },
        { "name": "ハイラル図鑑 魔物 20種登録（購入不可）", "en": "20 Monsters in Compendium(without purchase)", "types": ["Camera", "Compendium", "Compedium-Monster"] },
        { "name": "ミニチャレンジ:解放 さらなる力", "en": "Slated for Upgrades' Side Quest", "types": ["Camera", "Hateno", "Dueling Peaks", "Side Quest"] },
        { "name": "古代兵装武器", "en": "Ancient Weapon", "types": ["Rupee", "Weapon", "Castle", "Akkala"] },
        { "name": "防具14種", "en": "14 Armors", "types": ["Clothes", "Rupee"] },
        { "name": "夜光シリーズ一式を着て自撮り", "en": "Selfie wearing a set of Radiant series", "types": ["Rupee", "Camera", "Wasteland"] },
    ], [
        { "name": "ほこらチャレンジ 9つ攻略", "en": "9 Shrine Quests", "types": ["Shrine Quests", "Shrine", "Shrines"] },
        { "name": "ミニチャレンジ:ハイラルなぞなぞしれん", "en": "Riddles of Hyrule' Side Quest", "types": ["Riddles of Hyrule", "Boss Monster", "Woodland", "Side Quest"] },
        { "name": "ミニチャレンジ:巨大クジラの化石", "en": "Leviathan Bones' Side Quest", "types": ["Camera", "Eldin", "Wasteland", "Hebra", "Hateno", "Side Quest", ""] },
        { "name": "凍結無効", "en": "Unfreezable (without potion)", "types": ["Hebra", "Tabantha", "Rupee", "Great Fairy", "Clothes"] },
        { "name": "古代兵装弓", "en": "Ancient Bow", "types": ["Rupee", "Bow", "Castle", "Akkala"] },
    ], [
        { "name": "ハイラル図鑑 武器 30種登録（購入不可）", "en": "30 Equipment in Compendium(without purchase)", "types": ["Camera", "Compendium", "Compedium-Weapon", "Weapon"] },
        { "name": "ヒノックス10体討伐 (どの種でも可)", "en": "Kill 10 Hinox of any kind", "types": ["Kill", "Boss Monster", "Hinox"] },
        { "name": "ほこらチャレンジ 10つ攻略", "en": "10 Shrine Quests", "types": ["Shrine Quests", "Shrine", "Shrines"] },
        { "name": "ミニチャレンジ10個", "en": "10 Side Quests", "types": ["Side Quest", "Dueling Peaks"] },
        { "name": "古代兵装盾", "en": "Ancient Shield", "types": ["Rupee", "Shield", "Castle", "Akkala"] },
        { "name": "武器14種", "en": "14 Different Weapon", "types": ["Weapon", "Koroks", "Castle", "Central Hyrule", "Dueling Peaks"] },
        { "name": "雷無効", "en": "Unshockable (without potion)", "types": ["Rupee", "Great Fairy", "Clothes", "Ridgeland", "Faron"] },
    ], [
        { "name": "ウルボザの怒り", "en": "Urbosa's Fury", "types": ["Divine Beast", "MainQuest", "Gerudo", "Wasteland", "Champion's Abilities"] },
        { "name": "カッシーワのチャレンジ7種", "en": "7 Kass Quests", "types": ["Kass", "Shrine Quests", "Shrine", "Shrines", "Side Quest"] },
        { "name": "全ての塔を起動", "en": "Activate All Towers", "types": ["Tower"] },
        { "name": "ほこらチャレンジ 11つ攻略", "en": "11 Shrine Quests", "types": ["Shrine Quests", "Shrine", "Shrines"] },
        { "name": "古代兵装防具", "en": "Ancient Armor", "types": ["Rupee", "Clothes", "Castle", "Akkala"] },
        { "name": "大事なもの12枠", "en": "12 Different Key Items", "types": ["Minigame", "Key Items", "Horse Equipment"] },
    ], [
        { "name": "祠 20基攻略", "en": "20 Shrines", "types": ["Shrine", "Central Hyrule", "Shrines", "Spirit Orb"] },
        { "name": "ハイラル図鑑 生き物 30種登録（購入不可）", "en": "30 Creatures in Compendium(without purchase)", "types": ["Camera", "Compendium", "Compedium-Creature"] },
        { "name": "ほこらチャレンジ 12つ攻略", "en": "12 Shrine Quests", "types": ["Shrine Quests", "Shrine", "Shrines"] },
        { "name": "炎無効", "en": "Fireproof (without potion)", "types": ["Eldin", "Rupee", "Great Fairy", "Clothes"] },
    ], [
        { "name": "がんばりゲージ2周", "en": "5 Stamina Vessels", "types": ["Shrine"] },
        { "name": "ガーディアンを倒して力の試練の祠8基攻略", "en": "8 A Test of Strength while Killing Guardian Scout", "types": ["Guardian", "Shrine", "Akkala", "Shrines"] },
        { "name": "ハイラル図鑑 魔物 30種登録（購入不可）", "en": "30 Monsters in Compendium(without purchase)", "types": ["Camera", "Compendium", "Compedium-Monster"] },
        { "name": "ミニゲーム9種クリア", "en": "9 Minigames", "types": ["Minigame", "Lake", "Horse Equipment"] },
    ], [
        { "name": "ハイラル図鑑 武器 40種登録（購入不可）", "en": "40 Equipment in Compendium(without purchase)", "types": ["Camera", "Compendium", "Compedium-Weapon", "Weapon"] },
        { "name": "メインチャレンジ8個達成", "en": "8 MainQuests", "types": ["MainQuest", "Divine Beast", "Camera", "Hateno", "Champion's Abilities"] },
        { "name": "ラジークキラーの証", "en": "Medal of Honor: Molduga", "types": ["Kill", "Boss Monster", "Wasteland", "Akkala", "Molduga"] },
        { "name": "ほこらチャレンジ 13つ攻略", "en": "Medal of Honor: Molduga", "types": ["Shrine Quests", "Shrine", "Shrines"] },
    ], [
        { "name": "ライネル全討伐(23匹)", "en": "Kill All Lynels", "types": ["Castle", "Kill", "Boss Monster", "Lynel"] },
        { "name": "英傑能力2つ", "en": "2 Champion's Abilities", "types": ["Divine Beast", "MainQuest", "Champion's Abilities"] },
        { "name": "武器15種", "en": "15 Different Weapon", "types": ["Weapon", "Koroks", "Castle", "Central Hyrule", "Dueling Peaks", "Woodland", ""] },
    ], [
        { "name": "ヒノックス15体討伐 (どの種でも可)", "en": "Kill 15 Hinox of any kind", "types": ["Kill", "Boss Monster", "Hinox"] },
        { "name": "祠 25基攻略", "en": "25 Shrines", "types": ["Shrine", "Central Hyrule", "Shrines", "Spirit Orb"] },
        { "name": "ガーディアンを倒して力の試練の祠10基攻略", "en": "10 A Test of Strength while Killing Guardian Scout", "types": ["Guardian", "Shrine", "Akkala", "Shrines"] },
    ], [
        { "name": "ミニチャレンジ15個", "en": "15 Side Quests", "types": ["Side Quest", "Dueling Peaks"] },
        { "name": "メインチャレンジ：ウツシエの記憶", "en": "Captured Memories' Main Quest", "types": ["Camera", "Hateno", "Dueling Peaks"] },
        { "name": "加速泳ぎがんばり長持ち", "en": "Swim Dash Stamina Up", "types": ["Camera", "Lanayru", "Rupee", "Great Fairy", "Clothes"] },
    ], [
        { "name": "エノキダ結婚", "en": "Marriage", "types": ["Side Quest", "Rupee", "Hateno", "Akkala"] },
        { "name": "祠 28基攻略", "en": "28 Shrines", "types": ["Shrine", "Central Hyrule", "Shrines", "Spirit Orb"] },
        { "name": "大事なもの13枠", "en": "13 Different Key Items", "types": ["Minigame", "Key Items", "MainQuest", "Horse Equipment"] },
    ], [
        { "name": "ハイラル図鑑 生き物 40種登録（購入不可）", "en": "40 Creatures in Compendium(without purchase)", "types": ["Camera", "Compendium", "Compedium-Creature"] },
        { "name": "ミニゲーム10種クリア", "en": "10 Minigames", "types": ["Minigame", "Lake", "Horse Equipment"] },
        { "name": "メインチャレンジ9個達成", "en": "9 MainQuests", "types": ["MainQuest", "Divine Beast", "Camera", "Hateno", "Champion's Abilities"] },
    ], [
        { "name": "祠 30基攻略", "en": "30 Shrines", "types": ["Shrine", "Central Hyrule", "Shrines", "Spirit Orb"] },
        { "name": "ハイラル図鑑 魔物 40種登録（購入不可）", "en": "40 Monsters in Compendium(without purchase)", "types": ["Camera", "Compendium", "Compedium-Monster"] },
        { "name": "ミニチャレンジ: ゲルドの至宝 雷鳴の兜！", "en": "The Thunder Helm' Side Quest", "types": ["Side Quest", "Divine Beast", "MainQuest", "Gerudo", "Wasteland", "Champion's Abilities", ""] },
    ], [
        { "name": "武器16種", "en": "16 Different Weapon", "types": ["Weapon", "Koroks", "Castle", "Central Hyrule", "Dueling Peaks", "Woodland", ""] },
        { "name": "ミニチャレンジ:幼き武器マニア", "en": "The Weapon Connoisseur' Side Quest", "types": ["Hateno", "Rupee", "Weapon", "Castle", "Akkala"] },
        { "name": "ヒノックス20体討伐 (どの種でも可)", "en": "Kill 20 Hinox of any kind", "types": ["Kill", "Boss Monster", "Hinox"] },
    ], [
        { "name": "ここ掘れワンワンの全宝箱入手(16個)", "en": "All Dog Tresures", "types": ["Side Quest", "Rupee", "Hateno", "Akkala"] },
        { "name": "マモノ馬装備一式", "en": "Monster Saddle and Bridle", "types": ["Horse Equipment", "Divine Beast", "MainQuest", "Champion's Abilities"] },
        { "name": "ミニゲーム11種クリア", "en": "11 Minigames", "types": ["Minigame", "Lake", "Horse Equipment"] },
    ], [
        { "name": "ハイリアのフード★★★★", "en": "Hylian Hood★★★★", "types": ["Hateno", "Rupee", "Great Fairy", "Clothes", "Boko Parts"] },
        { "name": "ミニチャレンジ20個", "en": "20 Side Quests", "types": ["Side Quest", "Dueling Peaks", "Camera", "Akkala"] },
        { "name": "メインチャレンジ：勇者の剣", "en": "The Hero's Sword' Main Quest", "types": ["Shrine", "MainQuest", "Woodland", "Shrines", "Spirit Orb"] },
        { "name": "英傑能力3つ", "en": "3 Champion's Abilities", "types": ["Divine Beast", "MainQuest", "Champion's Abilities"] },
    ]
];